name: 'DocGen'
description: 'Analyze a repository with OpenAI using reusable prompts and open a PR with generated docs'
author: 'sappher'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  prompts-folder:
    description: 'Folder containing .md prompt files'
    required: false
    default: 'prompts'
  output-folder:
    description: 'Folder where AI outputs will be written'
    required: false
    default: 'generated-docs'
  openai-model:
    description: 'OpenAI model identifier (e.g., gpt-5-mini)'
    required: false
    default: 'gpt-5-mini'
  openai-api-key:
    description: 'OpenAI API key (use secrets)'
    required: true
  github-token:
    description: 'GitHub token with repo scope (e.g., secrets.GITHUB_TOKEN)'
    required: true
  exclude-patterns:
    description: 'Optional newline separated patterns to exclude from repo context'
    required: false
  max-file-size-bytes:
    description: 'Maximum individual file size to include in the model context'
    required: false
    default: '750000'
  max-repo-characters:
    description: 'Maximum pooled characters from repository files added to the model context'
    required: false
    default: '1000000'
  context-chunk-size:
    description: 'Approximate character size for each repository chunk'
    required: false
    default: '4000'
  temperature:
    description: 'OpenAI sampling temperature'
    required: false
    default: '0'
  branch-name:
    description: 'Branch to create/update for generated docs'
    required: false
  base-branch:
    description: 'Base branch for the pull request'
    required: false
  pr-title:
    description: 'Pull request title'
    required: false
  pr-body:
    description: 'Pull request body template'
    required: false
  dry-run:
    description: 'If true, skip git pushes and PR creation'
    required: false
    default: 'false'
  enable-git:
    description: 'Enable writing files and opening PRs in the repository'
    required: false
    default: 'false'
  enable-confluence:
    description: 'Enable publishing generated outputs to Confluence'
    required: false
    default: 'false'
  confluence-base-url:
    description: 'Base URL of the Confluence site (e.g., https://example.atlassian.net/wiki/)'
    required: false
  confluence-email:
    description: 'Confluence account email used with the API token'
    required: false
  confluence-api-token:
    description: 'Confluence API token (PAT) for authentication'
    required: false
  confluence-space-key:
    description: 'Optional Confluence space key when updating pages'
    required: false
  confluence-page-map:
    description: 'Mapping from prompt files to Confluence page IDs (JSON or newline key=value pairs)'
    required: false
  enable-embeddings:
    description: 'Use OpenAI embeddings to rank repository chunks before building context'
    required: false
    default: 'false'
  embeddings-model:
    description: 'Embeddings model identifier (e.g., text-embedding-3-large)'
    required: false
  max-embeddings-chunks:
    description: 'Optional hard cap on the number of top-ranked chunks per prompt when embeddings are enabled'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
