import fs from 'fs';
import path from 'path';

import * as core from '@actions/core';
import { context } from '@actions/github';

import { ActionInputs, CodexSandboxMode, ConfluenceSettings } from '../types/domain';

function coalesceInput(name: string, envName?: string): string {
  const actionValue = core.getInput(name);
  if (actionValue) {
    return actionValue.trim();
  }
  const envValue = process.env[envName ?? name.replace(/-/g, '_').toUpperCase()];
  return envValue ? envValue.trim() : '';
}

function coalesceBooleanInput(name: string, envName?: string, defaultValue = false): boolean {
  const actionProvided = core.getInput(name);
  if (actionProvided) {
    return /^true$/i.test(actionProvided.trim());
  }
  const envValue = process.env[envName ?? name.replace(/-/g, '_').toUpperCase()];
  if (envValue) {
    return /^true$/i.test(envValue.trim());
  }
  return defaultValue;
}

function normalizeRelativePath(input: string): string {
  return input
    .trim()
    .replace(/\\/g, '/')
    .replace(/^\.\/+/, '')
    .replace(/^\/+/, '');
}

export function parseConfluencePageMapInput(raw: string): Record<string, string> {
  if (!raw || !raw.trim()) {
    return {};
  }

  const normalizedInput = raw.trim();
  if (normalizedInput.startsWith('{')) {
    try {
      const parsed = JSON.parse(normalizedInput) as Record<string, string>;
      return Object.entries(parsed).reduce<Record<string, string>>((acc, [key, value]) => {
        if (!key || !value) {
          return acc;
        }
        acc[normalizeRelativePath(key)] = value.trim();
        return acc;
      }, {});
    } catch (error) {
      throw new Error(`Invalid JSON provided for confluence-page-map: ${(error as Error).message}`);
    }
  }

  const mapping: Record<string, string> = {};
  const lines = raw.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const [key, value] = trimmed.split('=');
    if (!key || !value) {
      throw new Error(
        `Invalid confluence-page-map entry "${line}". Expected format "prompt/path.md=1234567".`,
      );
    }
    const normalizedKey = normalizeRelativePath(key);
    mapping[normalizedKey] = value.trim();
  }
  return mapping;
}

function parseCodexSandboxMode(raw: string | undefined): CodexSandboxMode {
  const normalized = (raw ?? '').trim();
  if (!normalized) {
    return 'read-only';
  }

  if (
    normalized === 'read-only' ||
    normalized === 'workspace-write' ||
    normalized === 'danger-full-access'
  ) {
    return normalized;
  }

  throw new Error(
    `Invalid codex-sandbox "${normalized}". Expected read-only, workspace-write, or danger-full-access.`,
  );
}

export function getActionInputs(): ActionInputs {
  const workspacePath = process.env.GITHUB_WORKSPACE ?? process.cwd();
  const promptsFolderInput = coalesceInput('prompts-folder', 'PROMPTS_FOLDER') || 'prompts';
  const outputFolderInput = coalesceInput('output-folder', 'OUTPUT_FOLDER') || 'generated-docs';

  const promptsFolder = path.resolve(workspacePath, promptsFolderInput);
  const outputFolder = path.resolve(workspacePath, outputFolderInput);

  const gitPublisherEnabled = coalesceBooleanInput('enable-git', 'ENABLE_GIT', false);

  const githubToken =
    coalesceInput('github-token', 'GITHUB_TOKEN') || process.env.GITHUB_TOKEN || '';
  if (gitPublisherEnabled && !githubToken) {
    throw new Error(
      'Missing GitHub token. Provide it via the github-token input or env when enable-git is true.',
    );
  }

  const codexExecutable = coalesceInput('codex-executable', 'CODEX_EXECUTABLE') || 'codex';
  const codexModel = coalesceInput('codex-model', 'CODEX_MODEL') || undefined;
  const codexProfile = coalesceInput('codex-profile', 'CODEX_PROFILE') || undefined;
  const codexSandbox = parseCodexSandboxMode(
    coalesceInput('codex-sandbox', 'CODEX_SANDBOX') || process.env.CODEX_SANDBOX,
  );
  const codexConfigOverrides = core
    .getMultilineInput('codex-config', { trimWhitespace: true })
    .filter(Boolean);
  if (!codexConfigOverrides.length) {
    const envOverrides = process.env.CODEX_CONFIG;
    if (envOverrides) {
      codexConfigOverrides.push(
        ...envOverrides
          .split(/\r?\n/)
          .map((line) => line.trim())
          .filter(Boolean),
      );
    }
  }

  const branchNameInput = coalesceInput('branch-name', 'BRANCH_NAME');
  const runId = context.runId ?? Date.now();
  const runAttempt = context.runAttempt ?? 1;
  const defaultBranchName = `docgen/run-${runId}-${runAttempt}`;
  const branchName = branchNameInput || defaultBranchName;

  const baseBranch =
    coalesceInput('base-branch', 'BASE_BRANCH') || context.ref?.replace('refs/heads/', '') || 'main';

  const prTitle =
    coalesceInput('pr-title', 'PR_TITLE') || 'Codex-generated documentation and analysis updates';
  const prBodyTemplate =
    coalesceInput('pr-body', 'PR_BODY') ||
    'Automated updates generated by the docgen action. Please review the changes.';

  const dryRun = coalesceBooleanInput('dry-run', 'DRY_RUN', false);

  const repoFullName = process.env.GITHUB_REPOSITORY ?? '';
  if (!repoFullName) {
    throw new Error('GITHUB_REPOSITORY env is required when running inside GitHub Actions.');
  }

  const [repositoryOwner, repositoryName] = repoFullName.split('/', 2);

  const systemPromptFileInput = coalesceInput('system-prompt-file', 'SYSTEM_PROMPT_FILE');
  let systemPrompt: string | undefined;
  if (systemPromptFileInput) {
    const systemPromptPath = path.resolve(workspacePath, systemPromptFileInput);
    systemPrompt = loadSystemPrompt(systemPromptPath);
  }

  const enableConfluence = coalesceBooleanInput('enable-confluence', 'ENABLE_CONFLUENCE', false);
  let confluenceConfig: ConfluenceSettings | undefined;
  if (enableConfluence) {
    const baseUrl =
      coalesceInput('confluence-base-url', 'CONFLUENCE_BASE_URL') ||
      process.env.CONFLUENCE_BASE_URL ||
      '';
    const email =
      coalesceInput('confluence-email', 'CONFLUENCE_EMAIL') ||
      process.env.CONFLUENCE_EMAIL ||
      '';
    const apiToken =
      coalesceInput('confluence-api-token', 'CONFLUENCE_API_TOKEN') ||
      process.env.CONFLUENCE_API_TOKEN ||
      '';

    const spaceKey =
      coalesceInput('confluence-space-key', 'CONFLUENCE_SPACE_KEY') ||
      process.env.CONFLUENCE_SPACE_KEY ||
      '';

    const mapInputLines = core.getMultilineInput('confluence-page-map', {
      trimWhitespace: false,
    });
    const mapInput =
      mapInputLines.length > 0 ? mapInputLines.join('\n') : process.env.CONFLUENCE_PAGE_MAP || '';
    const pageMap = parseConfluencePageMapInput(mapInput);

    if (!baseUrl) {
      throw new Error('confluence-base-url is required when enable-confluence is true.');
    }
    if (!email) {
      throw new Error('confluence-email is required when enable-confluence is true.');
    }
    if (!apiToken) {
      throw new Error('confluence-api-token is required when enable-confluence is true.');
    }
    if (!Object.keys(pageMap).length) {
      throw new Error('confluence-page-map must define at least one mapping when Confluence is enabled.');
    }

    confluenceConfig = {
      enabled: true,
      baseUrl,
      email,
      apiToken,
      spaceKey: spaceKey || undefined,
      pageMap,
    };
  }

  return {
    workspacePath,
    promptsFolder,
    outputFolder,
    promptsFolderInput,
    outputFolderInput,
    codex: {
      executable: codexExecutable,
      model: codexModel,
      profile: codexProfile,
      sandbox: codexSandbox,
      configOverrides: codexConfigOverrides,
    },
    githubToken,
    branchName,
    baseBranch,
    prTitle,
    prBody: prBodyTemplate,
    dryRun,
    repoFullName,
    repositoryOwner,
    repositoryName,
    runId,
    runAttempt,
    systemPrompt,
    gitPublisherEnabled,
    confluence: confluenceConfig,
  };
}

function loadSystemPrompt(filePath: string): string {
  if (!fs.existsSync(filePath)) {
    throw new Error('file not found');
  }
  const content = fs.readFileSync(filePath, 'utf8').trim();
  if (!content) {
    throw new Error('file is empty');
  }
  return content;
}
